Updated beacon snapshots for sepolia/mainnet
ledgerwatch/erigon-snapshot pull request #114
Opened 2024-01-30 21:01 UTC by Giulio2002

2024-02-02 10:21 UTC, AskAlexSharov requested changes

2024-02-02 10:21 UTC, AskAlexSharov commented on mainnet.toml
> +'v1-000000-000500-bodies.seg' = 'e9b5c5d1885ee3c6ab6005919e511e1e04c7e34e'
something wrong with your terminal settings. probably you do copy it from the screen and it has some spaces in end of lines

2024-02-02 10:43 UTC, michelemodolo approved these changes

2024-02-13 09:51 UTC, AskAlexSharov approved these changes
re-formatted by myself

2024-02-13 09:51 UTC, merged